language: node_js

node_js:
  - '10.14.1'

sudo: true

env:
  global:
    - CXX=g++-4.8 NODE_ENV=testing
    - SECRET_KEY='secret_key'
    - ALBUMS_API_URL="https://jsonplaceholder.typicode.com"
    - PASSWORD_LENGTH=8
    - EMAIL_DOMAIN=@wolox.com.ar
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookstest;" -U postgres
  - npm run migrations-test
